# This is a basic workflow to help you get started with Actions

name: build vpp

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: initialize environment
        run: |
          sudo mkdir /work
          sudo chown $USER:$GROUPS /work
       
      - name: git clone vpp code
        working-directory: /work
        run: |
          git clone https://github.com/FDio/vpp.git
          ln -sf /work/vpp $GITHUB_WORKSPACE/vpp

      - name: make install-deps
        run: |
          pwd
          cd vpp
          git checkout stable/2009
          make install-deps
          
      - name: make install-ext-deps
        run: |
          cd vpp
          make install-ext-deps
          
      - name: make build-release
        run: |
          cd vpp
          make build-release
          
      - name: make pkg-deb
        run: |
          cd vpp
          make pkg-deb

      - name: mv pkg to release directory
        run: |
          mkdir -p /work/release
          cd vpp
          cp build-root/*.deb /work/release
          
      - name: upload release file 
        uses: liudf0716/upload-artifact@v2.2.2
        with:
         name: vpp_release
         path: /work/release
